### ISSUE TITLE
Thumbs does not show up

### ISSUE THREAD

**Issue by ghost** [nilfoer/mangadb#10]
I switched my os to ubuntu from windows so I uploaded my instance folder to gdrive to use it on new linux setup, everything seems fine except thumbs, it says no image even though they are in instance folder.

**Comment by nilfoer** [comment]
Maybe it's a permission problem? Make sure the `instance/thumbs` folder has `rwx` permissions.

**Comment by ghost** [comment]
It has rwx

**Comment by nilfoer** [comment]
Would you be willing to send me your files? Otherwise it's gonna be really hard to debug. (discord: nilfoer#9449)
