### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'func' error.

### ISSUE THREAD

**Issue by ghost** [nilfoer/mangadb#11]
Hi, I tried to do `./MangaDB --cookies instance/cookies.txt` and got [that](https://pastebin.ubuntu.com/p/CpC2thkq9P/)
Tried with `./MangaDB --cookies instance/cookies.txt  collect` cookies does not work with it too.

**Comment by nilfoer** [comment]
Should be fixed now.

I think you also mentioned sth. similar on discord and I fixed it right afterwards, but I forgot to upload the new version.

**Comment by ghost** [comment]
Yes it worked thank you, I got new error its about toonily should I open new issue?
