### ISSUE TITLE
Be able to add download status without external links.

### ISSUE THREAD

**Issue by ghost** [nilfoer/mangadb#13]
Hi! I meant this at the title, users may not track their download status because of if they are reading raw manga that has no eng translation probably they will not able to find the title on external sites.

**Comment by nilfoer** [comment]
If I understand this correctly you want to be able to add an external info entry manually for a site that is not supported?

**Comment by ghost** [comment]
Yes

**Comment by nilfoer** [comment]
You now can add links for unsupported sites see [here](https://github.com/nilfoer/mangadb/#adding-external-links)

**Comment by ghost** [comment]
It worked thank you!
