### ISSUE TITLE
Link collector does not download mangadex's covers.

### ISSUE THREAD

**Issue by ghost** [nilfoer/mangadb#4]
It does import flawlessly when I paste mangadex link to search bar and click import book but when I use link collector it does good job too but does not download covers.

**Comment by ghost** [comment]
Now, this import method does not work too, it redirects server 500 error.

**Comment by nilfoer** [comment]
Should be fixed in the new [release](https://github.com/nilfoer/mangadb/releases/tag/v0.21.1).

**Comment by ghost** [comment]
It works, thanks!
