### ISSUE TITLE
Is there way to Decapitalize automatically?

### ISSUE THREAD

**Issue by ghost** [nilfoer/mangadb#7]
Hi, Is there way the decaptilize automatically, I mean some manga website does have author's name different like Mangadex has "Inoue Takehiko" in mangasee his name written as "INOUE Takehiko" so is there way the convert it into automatically "Inou Takehiko". It may cause troubles like can not find mangas in MangaDB.

**Comment by nilfoer** [comment]
Artist names etc. are now converted to titlecase when importing them from a website. The search is also no longer case-sensitive so even if there are still values with weird cases? in your DB it shouldn't matter!

I also added an interface for renaming/deleting tags that you requested in #8.

**Comment by ghost** [comment]
Thank you!
